POST http://localhost:3003/api/blogs
Content-Type:  application/json

{

    "title": "Blog on the web - part2",
    "author": "Blog McMaker",
    "url": "https://www.blogmacmaker2.xyz/",
    "likes": 321
    
}