# fly.toml file generated for phonebook-backend-48d5sa4d4e84rew4f45ds4485few on 2023-03-28T16:22:13+02:00

app = "phonebook-backend-48d5sa4d4e84rew4f45ds4485few"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "arn"
processes = []

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
